"""Template engine — render a `MockConfig` schema/field into concrete values.

Walks a `FieldSpec` (or `SchemaConfig`) and produces a JSON-serialisable
Python object. Leaf values are generated by routing through the platform's
existing facilities:

  1. If `field.example` is set, return it (deterministic precedence).
  2. If `field.business_values` is set, pick one (deterministic with seed).
  3. If `field.special_rule` is set, route to `utils/helpers.py`.
  4. If `field.format` maps to a known special rule (email, uuid, iban,
     date-time, …), route to helpers.
  5. If `field.pattern` is set, generate via regex.
  6. Otherwise fall back to type-driven default (string → faker word, int →
     random in [min, max], etc.).

Nullability is honoured: when `nullable` is True and a Bernoulli draw under
`null_rate` succeeds, we emit `None`.

The engine is **stateless on the MockConfig** — it carries a reference to
the config so it can resolve `$ref`s, plus a single `random.Random` instance
so the same `--seed` produces byte-identical output across runs.
"""
from __future__ import annotations

import logging
import random
import string
import uuid
from datetime import date, datetime, timedelta, timezone
from typing import Any, Dict, List, Optional, Union

from models.mock_models import FieldSpec, MockConfig, SchemaConfig

logger = logging.getLogger(__name__)


# Map common OpenAPI `format:` values onto the platform's special rules.
_FORMAT_TO_SPECIAL: Dict[str, str] = {
    "email": "EMAIL",
    "uuid": "UUID",
    "uri": "URL",
    "url": "URL",
    "ipv4": "IPV4",
    "ipv6": "IPV6",
    "iban": "IBAN",
    "bic": "SWIFT",
    "swift": "SWIFT",
}


class TemplateEngine:
    """Render `FieldSpec` / `SchemaConfig` to concrete values.

    Use one engine per render run. Pass `seed` for determinism.
    """

    def __init__(
        self,
        config: MockConfig,
        seed: Optional[int] = None,
        *,
        ignore_authored_examples: bool = False,
    ):
        self.config = config
        self._rng = random.Random(seed)
        self._ignore_authored_examples = ignore_authored_examples
        # Some downstream helpers (regex generator, faker, mimesis) draw from
        # Python's global random + their own RNGs. Seed those too so the same
        # `seed` produces byte-identical output across the whole render path.
        if seed is not None:
            random.seed(seed)
            try:
                from faker import Faker
                Faker.seed(seed)
            except Exception:
                pass
        self._helpers = None  # lazy-init utils.helpers.DataHelpers

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def render_field(self, field: FieldSpec) -> Any:
        """Render any FieldSpec — entry point for callers."""
        # Early null check
        if field.nullable and field.null_rate and self._rng.random() < field.null_rate:
            return None

        # Authored example wins everything (unless caller disabled this rule)
        if field.example is not None and not self._ignore_authored_examples:
            return field.example

        # $ref — resolve and render the target SchemaConfig
        if field.ref:
            target = self.config.get_schema(field.ref)
            if target is None:
                logger.warning("Unresolvable $ref %r — emitting null", field.ref)
                return None
            return self.render_schema(target)

        # Inline object
        if field.type == "object" or field.properties:
            return self._render_object(field)

        # Inline array
        if field.type == "array":
            return self._render_array(field)

        # Primitives
        return self._render_primitive(field)

    def render_schema(self, schema: SchemaConfig) -> Any:
        """Render a top-level SchemaConfig (lives in MockConfig.schemas)."""
        if schema.example is not None and not self._ignore_authored_examples:
            return schema.example

        if schema.type == "array":
            length = self._rng.randint(2, 5)
            return [self.render_field(schema.items) for _ in range(length)]

        # Treat object (or anything with properties) the same way
        out: Dict[str, Any] = {}
        for prop_name, field in schema.properties.items():
            out[prop_name] = self.render_field(field)
        return out

    def render_endpoint_response(
        self, endpoint_name: str, status: Optional[int] = None
    ) -> Any:
        """Convenience: render the body of one endpoint response variant.

        If `status` is None, picks the first variant (already 2xx-first thanks
        to the importer's sort). When the variant has no body schema and no
        body template, returns None.
        """
        ep = self.config.get_endpoint(endpoint_name)
        if ep is None:
            raise KeyError(f"unknown endpoint: {endpoint_name!r}")
        if status is None:
            response = ep.responses[0]
        else:
            response = next((r for r in ep.responses if r.status == status), None)
            if response is None:
                raise KeyError(f"{endpoint_name} has no response with status {status}")

        if response.body_template is not None:
            return self._render_template_string(response.body_template)
        if response.body_schema is None:
            return None
        return self.render_field(response.body_schema)

    # ------------------------------------------------------------------
    # Inline object / array
    # ------------------------------------------------------------------
    def _render_object(self, field: FieldSpec) -> Dict[str, Any]:
        out: Dict[str, Any] = {}
        for prop_name, child in (field.properties or {}).items():
            out[prop_name] = self.render_field(child)
        return out

    def _render_array(self, field: FieldSpec) -> List[Any]:
        if field.items is None:
            return []
        # Heuristic: a small but >0 length so consumers see a populated list.
        # Honour min_length / max_length when authors set them.
        lo = field.min_length or 2
        hi = field.max_length or max(lo, 5)
        if hi < lo:
            hi = lo
        length = self._rng.randint(lo, hi)
        return [self.render_field(field.items) for _ in range(length)]

    # ------------------------------------------------------------------
    # Primitives
    # ------------------------------------------------------------------
    def _render_primitive(self, field: FieldSpec) -> Any:
        # business_values takes precedence over type — it's an enum
        if field.business_values:
            return self._rng.choice(list(field.business_values))

        # special_rule → platform's value generators
        if field.special_rule:
            return self._call_special_rule(field.special_rule, field)

        # format hint → maybe a special rule
        if field.format and field.format in _FORMAT_TO_SPECIAL:
            return self._call_special_rule(_FORMAT_TO_SPECIAL[field.format], field)

        # date/datetime formats
        if field.format == "date":
            return self._random_date().isoformat()
        if field.format in ("date-time", "datetime"):
            return self._random_datetime().isoformat()

        # regex
        if field.pattern:
            return self._generate_from_regex(field.pattern, field.max_length)

        # type-driven defaults
        t = (field.type or "string").lower()
        if t == "string":
            return self._random_string(field)
        if t in ("integer", "int", "long"):
            return self._random_int(field)
        if t in ("number", "float", "double"):
            return self._random_number(field)
        if t in ("boolean", "bool"):
            return self._rng.choice([True, False])

        # platform types (VA32, N10, DC, …) — best-effort dispatch
        if t.startswith("va"):
            return self._random_string(field)
        if t.startswith("n"):
            return self._random_int(field)
        if t == "dc":
            return self._random_number(field)

        # Fallback
        return self._random_string(field)

    # ------------------------------------------------------------------
    # Helper-backed value generators
    # ------------------------------------------------------------------
    def _call_special_rule(self, rule: str, field: FieldSpec) -> Any:
        """Bridge to utils/helpers.DataHelpers.generate_special_value."""
        helpers = self._get_helpers()
        if helpers is None:
            return self._fallback_for_special_rule(rule)
        try:
            data_type = field.type or "string"
            return helpers.generate_special_value(
                special_rule=rule,
                data_type=data_type,
                column_name=None,
                max_length=field.max_length,
            )
        except Exception as exc:
            logger.warning(
                "special_rule %r failed (%s) — falling back to deterministic stub",
                rule, exc,
            )
            return self._fallback_for_special_rule(rule)

    def _generate_from_regex(self, pattern: str, max_length: Optional[int]) -> str:
        helpers = self._get_helpers()
        if helpers is None:
            # Without helpers we can't reliably generate — return a literal-ish stub
            return pattern
        try:
            return helpers.generate_from_regex_rule(f"REGEX:{pattern}", max_length=max_length)
        except Exception:
            return pattern

    def _get_helpers(self):
        if self._helpers is not None:
            return self._helpers
        try:
            from utils.helpers import DataHelpers
            self._helpers = DataHelpers()
        except Exception as exc:
            logger.warning("DataHelpers unavailable (%s) — using deterministic fallbacks", exc)
            self._helpers = None
        return self._helpers

    # ------------------------------------------------------------------
    # Deterministic fallbacks (no helpers)
    # ------------------------------------------------------------------
    def _fallback_for_special_rule(self, rule: str) -> str:
        rule = rule.upper()
        if rule == "EMAIL":
            return f"user{self._rng.randint(100, 999)}@example.com"
        if rule == "UUID":
            return str(uuid.UUID(int=self._rng.getrandbits(128)))
        if rule == "URL":
            return f"https://example.com/{self._rng.randint(1000, 9999)}"
        if rule == "IPV4":
            return ".".join(str(self._rng.randint(1, 254)) for _ in range(4))
        if rule == "IPV6":
            return ":".join(f"{self._rng.randint(0, 0xffff):x}" for _ in range(8))
        if rule == "IBAN":
            cc = self._rng.choice(["DE", "GB", "FR", "ES", "NL"])
            check = f"{self._rng.randint(10, 99):02d}"
            body = "".join(self._rng.choices(string.digits, k=16))
            return cc + check + body
        if rule == "SWIFT":
            return "".join(self._rng.choices(string.ascii_uppercase, k=8))
        return f"VAL_{self._rng.randint(1000, 9999)}"

    def _random_string(self, field: FieldSpec) -> str:
        lo = field.min_length or 6
        hi = field.max_length or max(lo, 12)
        if hi < lo:
            hi = lo
        length = self._rng.randint(lo, hi)
        return "".join(self._rng.choices(string.ascii_letters, k=length))

    def _random_int(self, field: FieldSpec) -> int:
        lo = int(field.minimum) if field.minimum is not None else 1
        hi = int(field.maximum) if field.maximum is not None else max(lo, 9999)
        if hi < lo:
            hi = lo
        return self._rng.randint(lo, hi)

    def _random_number(self, field: FieldSpec) -> float:
        lo = float(field.minimum) if field.minimum is not None else 0.0
        hi = float(field.maximum) if field.maximum is not None else max(lo, 1000.0)
        if hi < lo:
            hi = lo
        return round(self._rng.uniform(lo, hi), 2)

    def _random_date(self) -> date:
        # Within ±5 years of today — narrow enough to look realistic, wide
        # enough to vary across regenerations.
        days = self._rng.randint(-365 * 5, 365 * 5)
        return date.today() + timedelta(days=days)

    def _random_datetime(self) -> datetime:
        days = self._rng.randint(-365 * 5, 365 * 5)
        seconds = self._rng.randint(0, 86399)
        # ISO 8601 with timezone — most JSON consumers want this.
        return datetime.now(timezone.utc) + timedelta(days=days, seconds=seconds)

    # ------------------------------------------------------------------
    # Body template (Jinja-style placeholder substitution)
    # ------------------------------------------------------------------
    def _render_template_string(self, template: str) -> str:
        """Very small `{{ schema_name }}` substitution for raw body templates.

        Real Jinja support is a possible upgrade, but for now we resolve
        ``{{ X }}`` to a JSON-serialised render of `MockConfig.schemas[X]`.
        """
        import json
        out = template
        # Find ``{{ name }}`` placeholders
        i = 0
        while True:
            start = out.find("{{", i)
            if start == -1:
                break
            end = out.find("}}", start + 2)
            if end == -1:
                break
            name = out[start + 2:end].strip()
            schema = self.config.get_schema(name)
            replacement = json.dumps(self.render_schema(schema)) if schema else ""
            out = out[:start] + replacement + out[end + 2:]
            i = start + len(replacement)
        return out
